"""Canonical 2x2 table: evidence head (T4 vs T0) x augmentation (CEM v1 vs none), seed 0.

Reads the four evaluated runs and writes results/table_2x2.json and results/table_2x2.md:
per-arm metrics, and the four paired contrasts (evidence effect with and without CEM, CEM effect
with and without evidence) with paired bootstrap CIs over dev paragraphs / edit pairs, from
compare.compare(). Every number traces to <run>/eval/*.json|jsonl and <run>/best.pt.
Run: ..\\torch_env\\Scripts\\python.exe code\\factorial.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from compare import compare  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RUNS_BY_CEM = {
    "v1": {"T4+CEM": ROOT / "results/pilot/T4_s0", "T0+CEM": ROOT / "results/pilot/T0_s0",
           "T4 noCEM": ROOT / "results/ablation/T4nc_s0", "T0 noCEM": ROOT / "results/ablation/T0nc_s0"},
    "v2": {"T4+CEM": ROOT / "results/cemv2/T4v2_s0", "T0+CEM": ROOT / "results/cemv2/T0v2_s0",
           "T4 noCEM": ROOT / "results/ablation/T4nc_s0", "T0 noCEM": ROOT / "results/ablation/T0nc_s0"},
}
CEM = sys.argv[1] if len(sys.argv) > 1 else "v1"
RUNS = RUNS_BY_CEM[CEM]
SUFFIX = "" if CEM == "v1" else "_cemv2"
CONTRASTS = [("full system vs plain fine-tuning", "T4+CEM", "T0 noCEM"),
             ("evidence effect given CEM", "T4+CEM", "T0+CEM"),
             ("evidence effect without CEM", "T4 noCEM", "T0 noCEM"),
             ("CEM effect given evidence head", "T4+CEM", "T4 noCEM"),
             ("CEM effect on label-only model", "T0+CEM", "T0 noCEM")]


def fmt(x, nd=3):
    return "-" if x is None else f"{x:.{nd}f}"


def ci(c):
    return f"[{c[0]:+.3f}, {c[1]:+.3f}]"


def main() -> None:
    arms, versions = {}, set()
    for name, d in RUNS.items():
        m = json.loads((d / "eval" / "metrics.json").read_text())
        versions.add(m.get("eval_version"))
        f2 = m.get("faithfulness_v2", {})
        arms[name] = {
            "micro_f1": m["label_mode"]["micro_f1"], "macro_f1": m["label_mode"]["macro_f1"],
            "span_mode_f1": m.get("span_mode", {}).get("micro_f1"),
            "label_ece_temp": m["label_calibration"]["ece_temp"],
            "top1_hit": m.get("evidence", {}).get("top1_hit"),
            "recall3": m.get("evidence", {}).get("gold_recall_top3"),
            "cited_ece_raw": m.get("cited_span_calibration", {}).get("ece_raw"),
            "cited_ece_platt": m.get("cited_span_calibration", {}).get("ece_platt"),
            "aurc": m.get("selective", {}).get("aurc"),
            "comprehensiveness": m.get("comprehensiveness", {}).get("diff"),
            **{f"v2_{k}": v["stat"] for k, v in f2.items()},
            "p50_ms": m.get("latency", {}).get("p50_ms"),
            "para_per_s": m.get("latency", {}).get("throughput_para_per_s_bs32"),
            "ckpt": str(d / "best.pt"),
        }
    if len(versions) != 1 or None in versions:
        raise SystemExit(f"runs were evaluated with different evaluator versions: {versions}")
    contrasts = {lab: compare(RUNS[a], RUNS[b]) for lab, a, b in CONTRASTS}
    (ROOT / "results" / f"table_2x2{SUFFIX}.json").write_text(json.dumps(
        {"arms": arms, "contrasts": contrasts}, indent=2))

    L = [f"# 2x2: evidence head x CEM {CEM} (seed 0, dev 3,127 paragraphs)", "",
         "Generated by `code/factorial.py` from `<run>/eval/`. One seed: CIs are over dev "
         "paragraphs or edit pairs, not over training seeds.", "",
         "| Arm | micro-F1 | macro-F1 | span-mode F1 | label ECE | AURC | top-1 hit | recall@3 | "
         "cited ECE raw / Platt | comprehensiveness | KILL | INJECT | SWAP | RELOC* | SUFF* |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for n, a in arms.items():
        L.append(f"| {n} | {fmt(a['micro_f1'])} | {fmt(a['macro_f1'])} | {fmt(a['span_mode_f1'])} | "
                 f"{fmt(a['label_ece_temp'], 4)} | {fmt(a['aurc'], 4)} | {fmt(a['top1_hit'])} | "
                 f"{fmt(a['recall3'])} | {fmt(a['cited_ece_raw'])} / {fmt(a['cited_ece_platt'])} | "
                 f"{fmt(a['comprehensiveness'])} | "
                 f"{fmt(a.get('v2_KILL'))} | {fmt(a.get('v2_INJECT'))} | {fmt(a.get('v2_SWAP'))} | "
                 f"{fmt(a.get('v2_RELOC'))} | {fmt(a.get('v2_SUFF'))} |")
    L += ["", "KILL/INJECT/SWAP/RELOC/SUFF: CEM v2 edit-minus-matched-control effect on p_t. "
          "Expected signs for a faithful model: KILL < 0 (evidence deleted); INJECT > 0 (real "
          "evidence inserted); SWAP < 0 (measured on the technique whose evidence was replaced); "
          "RELOC = |edit| - |control| near 0 (moving evidence should not matter); SUFF > 0 "
          "(evidence alone vs same-shape text alone). * = held-out families, never used in any "
          "training set; KILL/INJECT/SWAP resemble the v1 training edits.", "",
          "## Paired contrasts (a - b, 95% CI)", "",
          "| Contrast | micro-F1 | KILL | INJECT | SWAP | RELOC* | SUFF* |", "|---|---|---|---|---|---|---|"]
    for lab, a, b in CONTRASTS:
        c = contrasts[lab]
        cells = [f"{c['micro_f1']['diff']:+.3f} {ci(c['micro_f1']['diff_ci95'])}"]
        for fam in ("KILL", "INJECT", "SWAP", "RELOC", "SUFF"):
            f = c.get("faithfulness_v2", {}).get(fam)
            cells.append("-" if not f else f"{f['a_minus_b']:+.3f} {ci(f['a_minus_b_ci95'])}")
        L.append(f"| {lab} ({a} vs {b}) | " + " | ".join(cells) + " |")
    (ROOT / "results" / f"table_2x2{SUFFIX}.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
